
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "linmaxi@gmail.com",
    "password" : "77271234"
}
###
POST http://localhost:3000/assignment
Content-Type: application/json

[
    {
        "searchPhrase" : "software",
        "amount": 2,
        "note" : "שלום, נעים מאוד! אשמח לקונקט =]"
    },
    {
        "searchPhrase" : "wix HR",
        "amount": 3,
        "note" : "שלום, נעים מאוד!! אשמח לקונקט =]"
    },
    {
        "searchPhrase" : "checkpoint HR",
        "amount": 3,
        "note" : "שלום, נעים מאוד!! אשמח לקונקט =]"
    }
]
###
POST http://localhost:3000/logout 

###
POST http://localhost:3000/checkConnects